---
# tasks for consul
- user: name=consul

- group: name=consul

- get_url: url=https://dl.bintray.com/mitchellh/consul/{{ version }}_linux_amd64.zip
  args:
    dest: /tmp
    mode: 0644
    sha256sum: "{{ sha256sum }}"

- command: unzip -o /tmp/{{ version }}_linux_amd64.zip chdir=/usr/local/bin
  notify:
    - restart consul

- file: path=/usr/local/bin/consul owner=consul group=consul mode=0755 state=file

- file: path={{ item }} owner=consul group=consul mode=0755 state=directory
  with_items:
    - /etc/consul.d
    - "{{ data_dir }}"

- copy: src=./etc/init.d/consul dest=/etc/init.d/consul owner=consul group=consul mode=0755

- template: src=./etc/consul.conf dest=/etc/consul.conf owner=consul group=consul mode=0644
  notify:
    - restart consul

